---
version: '3'
networks: 
  rmoff:
    name: rmoff
    driver: bridge
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    networks: 
      - rmoff
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: wurstmeister/kafka
    container_name: broker
    networks: 
      - rmoff
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOSTNAME: localhost
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://broker:29090,LISTENER_EXTERNAL://localhost:9090
      KAFKA_LISTENERS: LISTENER_INTERNAL://broker:29090, LISTENER_EXTERNAL://localhost:9090
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      ALLOW_PLAINTEXT_LISTENER: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "sendMessage:1:1,recieveMessage:1:1"
  front:
     image: lantum1/front_mai
     container_name: front
     networks: 
      - rmoff
     ports:
      - "3000:3000"
  nginx:
    container_name: nginx_serv
    image: lantum1/front_mai
    depends_on:
      - front
    networks: 
      - rmoff
    restart: always
    ports:
      - "80:3000"
  clickhouse:
    image: yandex/clickhouse-server
    networks: 
      - rmoff
    volumes:
      - ./opt/clickhouse/etc/users.xml:/etc/clickhouse-server/users.xml
      - ./opt/clickhouse/etc/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "9000:9000"
      - "8123:8123"
