---
version: '3'
networks: 
  rmoff:
    name: rmoff
    driver: bridge
services:
  front:
     container_name: front
     build:
      dockerfile: Dockerfile
      context: ../Delivery.Front
     networks: 
      - rmoff
     ports:
      - "3000:3000"
  nginx:
    container_name: nginx_serv
    depends_on:
      - front
    networks: 
      - rmoff
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  clickhouse:
    image: yandex/clickhouse-server
    networks: 
      - rmoff
    volumes:
      - ./opt/clickhouse/etc/users.xml:/etc/clickhouse-server/users.xml
      - ./opt/clickhouse/etc/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "9000:9000"
      - "8123:8123"
